import { getSiteUrl } from '@/lib/siteUrl';
import { SEO_PAGE_SLUGS, getSeoPageMetadata } from '@/seo-landing/meta';
import { fetchBlogs } from '@/lib/blogApi';

/**
 * All 200 planned blog slugs from the content plan.
 * These are included in the sitemap immediately so Google can discover
 * them even before the posts are fully published in the DB.
 */
const PLANNED_BLOG_SLUGS = [
  'best-construction-management-software-india-2025',
  'manage-construction-projects-mobile-india',
  'top-10-features-contractor-software',
  'civil-contractor-app-thekedaar-2025',
  'construction-site-management-app-guide',
  'online-construction-software-vs-paper-register',
  'free-construction-management-app-small-contractors',
  'how-thekedaari-helps-civil-contractors',
  'construction-project-tracking-software-overview',
  'indian-contractors-switching-digital-management',
  'labour-management-app-construction-india',
  'majdoor-hisaab-kitab-app-contractors',
  'calculate-labour-cost-per-day-construction',
  'daily-labour-attendance-app-construction',
  'manage-50-workers-construction-site',
  'worker-ledger-app-track-payments',
  'karigar-hisaab-app-skilled-workers',
  'record-labour-advance-payment-construction-app',
  'labour-salary-calculation-app-contractors',
  'half-day-attendance-construction-labour-app',
  'add-workers-construction-app-guide',
  'construction-labour-roles-karigar-contractor',
  'view-full-labour-ledger-thekedaari',
  'daily-wage-record-app-reduce-disputes',
  'pay-workers-record-payment-construction-app',
  'add-new-construction-project-thekedaari',
  'project-wise-income-expense-tracking',
  'track-multiple-construction-projects',
  'construction-project-finance-dashboard-daily',
  'running-completed-projects-status-app',
  'classify-construction-projects-small-medium-big',
  'search-projects-construction-management-app',
  'project-summary-report-income-expense-profit',
  'close-completed-construction-project-app',
  'construction-project-profitability-digital',
  'record-construction-site-income-thekedaari',
  'track-material-expenses-construction-site',
  'construction-expense-categories',
  'record-theka-contract-work-expenses',
  'income-vs-expense-report-contractors',
  'avoid-budget-overrun-construction-projects',
  'digital-cashbook-contractors-replace-paper',
  'cash-online-payment-tracking-construction',
  'see-total-project-spending-realtime',
  'construction-site-petty-cash-management',
  'labour-attendance-management-construction',
  'daily-labour-attendance-mobile-app',
  'attendance-report-construction-site',
  'attendance-tracking-reduces-labour-cost',
  'full-day-half-day-attendance-construction-app',
  'project-wise-attendance-report-multiple-sites',
  'mark-absent-workers-construction-app',
  'link-attendance-payment-thekedaari',
  'biometric-vs-app-attendance-construction',
  'monthly-labour-attendance-summary-payroll',
  'manage-subcontractors-construction-project',
  'theka-work-management-app-india',
  'add-theka-types-construction-app',
  'contractor-payment-tracking-app',
  'settle-final-account-construction-contractor',
  'roles-permissions-construction-management-app',
  'categorise-workers-labour-karigar-contractor',
  'plumbing-contractor-management-app',
  'electrical-contractor-expense-tracking',
  'create-master-data-roles-theka-types',
  'thekedaar-app-kaise-use-karein-hindi-guide',
  'majdoor-ka-hisaab-digital-2025',
  'construction-software-hindi-contractor-best-app',
  'labour-hisaab-app-rozana-kharcha-track',
  'contractor-best-mobile-app-profit',
  'find-clients-construction-business-online-india',
  'construction-business-scale-2-to-20-sites',
  'reduce-construction-project-costs-tips',
  'construction-site-daily-report-maintain',
  'profit-loss-statement-construction-projects',
  'register-thekedaari-app-guide',
  'login-thekedaari-construction-app',
  'thekedaari-dashboard-explained',
  'thekedaari-side-menu-navigation-features',
  'transactions-report-thekedaari-guide',
  'top-5-problems-contractors-face-solutions',
  'prevent-labour-payment-disputes-construction',
  'construction-site-safety-management-checklist',
  'digital-tools-changing-indian-construction',
  'construction-project-planning-start-to-end',
  'material-purchase-record-construction-avoid-waste',
  'construction-labour-productivity-track-improve',
  'manage-construction-site-remotely-mobile-app',
  'construction-cost-estimation-vs-actual',
  'year-end-financial-review-construction-contractors',
  'thekedaari-vs-excel-construction-management',
  'thekedaari-vs-notebook-register-digital',
  'app-vs-whatsapp-construction-management',
  'cloud-construction-software-vs-offline',
  'free-vs-paid-construction-management-app',
  'update-worker-profile-thekedaari',
  'change-password-thekedaari-app',
  'thekedaari-first-time-setup-guide',
  'add-photos-worker-profiles-thekedaari',
  'export-download-reports-construction-app',
  'thekedaari-offline-mode-guide',
  'add-project-start-date-timeline-thekedaari',
  'record-worker-salary-earning-manually',
  'handle-worker-leaves-mid-project',
  'thekedaari-multiple-contractors-supervisors',
  'types-construction-contracts-india',
  'construction-labour-laws-india-contractors',
  'muster-roll-construction-digital',
  'construction-project-phases-planning-execution',
  'gst-affects-construction-contractors-india',
  'minimum-wage-construction-labour-india-2025',
  'pf-esi-construction-workers-contractors',
  'skilled-unskilled-labour-wage-india',
  'handle-labour-shortage-construction-sites',
  'common-construction-mistakes-cost-contractors',
  'construction-app-residential-building',
  'construction-app-commercial-building',
  'road-construction-project-management-app',
  'home-renovation-contractor-app-small-projects',
  'government-construction-project-digital',
  'independent-civil-contractor-app',
  'interior-work-contractor-app-tracking',
  'construction-foreman-app-supervisor',
  'thekedaari-contractors-rajasthan',
  'thekedaari-contractors-up-bihar-labour',
  'view-balance-due-worker-before-payday',
  'correct-wrong-attendance-entry-thekedaari',
  'delete-edit-expense-entry-thekedaari',
  'transactions-module-thekedaari-guide',
  'thekedaari-data-backup-security',
  'share-construction-reports-client-thekedaari',
  'worker-wise-total-salary-report',
  'filter-attendance-date-range-thekedaari',
  'project-income-installments-thekedaari',
  'best-practices-daily-construction-data-entry',
  'grow-construction-business-data-reports',
  'notebook-to-app-contractor-digital-management',
  'impress-clients-professional-construction-reports',
  'construction-business-kpis-contractor-track',
  'build-trusted-construction-brand-digital',
  'construction-app-painting-contractors',
  'construction-app-tile-work-contractors-india',
  'construction-app-shuttering-centering',
  'construction-app-waterproofing-contractors',
  'manage-rcc-slab-construction-labour-cost',
  'brick-masonry-labour-management-app',
  'carpenter-labour-hisaab-app-construction',
  'steel-work-contractor-app-labour-material',
  'excavation-earthwork-contractor-app',
  'flooring-contractor-app-labour-material',
  'construction-season-planning-peak-period',
  'monsoon-construction-site-management',
  'manage-labour-festival-season-construction',
  'year-end-project-audit-contractors',
  'plan-labour-hiring-new-construction-project',
  'worker-balance-wrong-fix-thekedaari',
  'forgot-thekedaari-password-what-to-do',
  'contractor-mobile-app-vs-diary',
  'worker-two-different-daily-rates',
  'current-balance-worker-ledger-explained',
  'multiple-users-one-thekedaari-account',
  'take-attendance-20-workers-2-minutes',
  'data-change-phone-thekedaari-faq',
  'add-site-supervisor-user-thekedaari',
  'construction-app-troubleshooting-guide',
  'construction-industry-india-2025-stats',
  'construction-project-cost-india-2025',
  'average-daily-wage-construction-workers-india-2025',
  'workers-typical-indian-construction-site',
  'top-10-states-construction-activity-india',
  'track-client-payment-instalments-construction',
  'manage-pending-payments-clients-construction',
  'cash-flow-management-construction-contractors',
  'calculate-net-profit-construction-project',
  'track-material-purchase-credit-suppliers',
  'labour-payment-schedule-weekly-monthly',
  'record-upi-payment-workers-construction-app',
  'security-deposit-management-construction',
  'retention-money-construction-track',
  'running-account-bill-construction-projects',
  'why-thekedaari-best-construction-app-india',
  'thekedaari-app-review-features-pros-cons',
  'thekedaari-app-free-pricing-plans',
  'thekedaari-vs-other-construction-apps',
  'who-made-thekedaari-story',
  'calculate-project-labour-cost-attendance',
  'construction-app-self-employed-contractors',
  'prepare-final-bill-construction-project',
  'worker-transfer-between-projects-thekedaari',
  'construction-loan-finance-tracking-contractors',
  'use-thekedaari-app-android-mobile',
  'construction-software-tier-2-tier-3-india',
  'save-time-site-administration-thekedaari',
  'construction-project-account-book-digital-paper',
  'manage-night-shift-labour-construction',
  'labour-contract-vs-daily-wage-contractors',
  'track-equipment-machinery-cost-construction',
  'construction-site-register-paperless-2025',
  'thekedaari-contact-support-guide',
  'getting-started-thekedaari-complete-guide',
];

/** Public marketing URLs that should be discoverable by search engines. */
export default async function sitemap() {
  const base = getSiteUrl();
  const now = new Date();

  const main = [
    { path: '', changeFrequency: 'weekly', priority: 1 },
    { path: '/login', changeFrequency: 'monthly', priority: 0.6 },
    { path: '/register', changeFrequency: 'monthly', priority: 0.7 },
    { path: '/contact-us', changeFrequency: 'monthly', priority: 0.5 },
    { path: '/how-to-use', changeFrequency: 'monthly', priority: 0.5 },
    { path: '/about-us', changeFrequency: 'monthly', priority: 0.7 },
    { path: '/privacy-policy', changeFrequency: 'yearly', priority: 0.4 },
    { path: '/blogs', changeFrequency: 'daily', priority: 0.85 },
  ];

  const seo = SEO_PAGE_SLUGS.map((slug) => {
    const m = getSeoPageMetadata(slug);
    const path = new URL(m.alternates.canonical).pathname;
    return { path, changeFrequency: 'weekly', priority: 0.9 };
  });

  // Fetch live blogs from DB (published ones only)
  const liveBlogs = await fetchBlogs().catch(() => []);
  const liveSlugs = new Set(liveBlogs.map((b) => b.slug));

  // Live blog entries (with real createdAt dates)
  const liveBlogEntries = liveBlogs.map((b) => ({
    url: `${base}/blogs/${b.slug}`,
    lastModified: b.createdAt ? new Date(b.createdAt) : now,
    changeFrequency: 'monthly',
    priority: 0.8,
  }));

  // Planned blog entries not yet in DB — still indexed for discovery
  const plannedBlogEntries = PLANNED_BLOG_SLUGS.filter((s) => !liveSlugs.has(s)).map((slug) => ({
    url: `${base}/blogs/${slug}`,
    lastModified: now,
    changeFrequency: 'monthly',
    priority: 0.75,
  }));

  const staticEntries = [...main, ...seo].map(({ path, changeFrequency, priority }) => ({
    url: `${base}${path}`,
    lastModified: now,
    changeFrequency,
    priority,
  }));

  return [...staticEntries, ...liveBlogEntries, ...plannedBlogEntries];
}
